### ISSUE TITLE
🐛 [BUG] - review's Issue Template Bug

### ISSUE THREAD

**Issue by hwna00** [AgainIoT/Open-Set-Go#68]
### Browsers

Others

### OS

Mac

### Description

open-set-go를 통해 이슈 템플릿을 생성했을 때, 파일 이름이 undefined.yml 로 생성되는 버그가 발생한다.

### Reproduction URL

https://github.com/hwna00/2023ESWContest_webOS_3015/pull/263

### Reproduction Steps

review 기능의 이슈 템플릿을 생성했을 떄, 템플릿 파일의 이름이 undefined로 생성된다.

### Screenshots

<img width="741" alt="스크린샷 2023-11-04 오후 12 53 13" src="https://github.com/AgainIoT/Open-Set-Go/assets/61866802/36a8b76b-1bde-441a-a937-f5af42efb9ef">

**Comment by ymw0407** [comment]
우선, 베타테스트에 이어서 버그리포트를 제출해주셔서 감사하다는 말씀을 드립니다. 해당 Issue는 https://github.com/AgainIoT/Open-Set-Go_client/issues/207 에서 처리되어 Open-Set-Go v2.0.1에서 적용될 예정임을 말씀드립니다!
